server:
  port: 13000
  servlet:
    context-path: /gw-merchant-api

#Feign请求超时时间
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

#开启熔断器
feign:
  sentinel:
    enabled: true

spring:
  application:
    name: cloud-service-merchant-api

  cloud:
    #熔断器
    sentinel:
      transport:
        port: ${server.port}
        dashboard: 45.125.218.106:8002

    #nacos配置
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848


logging:
  level:
    com.xinbo: debug
  file:
    max-size: 5MB
  path: ./logs/


zookeeper:
  server-addr: 45.125.218.106:2181,45.125.218.106:2182,45.125.218.106:2183
  session-timeout: 120000

rocketmq:
  name-server: 45.125.218.106:9876
  producer-group: sport_rocketmq_producer_group
  producer-timeout: 300000