server:
  port: 13000
spring:
  application:
    name: cloud-service-merchant-api
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.30.88:8848
    sentinel:
      transport:
        dashboard: 192.168.30.88:8002
logging:
  level:
    com.xinbo: debug
  file:
    max-size: 5MB
    name: ./logs/${spring.application.name}.log
    max-history: 10
dubbo:
  scan:
    base-packages: com.xinbo.cloud.service.merchant.api
  protocol:
    name: dubbo
    port: -1
  consumer:
    check: false
    generic: false
  registry:
    address: 192.168.30.88:8848
    check: false
zookeeper:
  server-addr: 192.168.30.88:2181,192.168.30.88:2182,192.168.30.88:2183
  session-timeout: 120000
rocketmq:
  name-server: 192.168.30.88:9876
  producer-group: sport_rocketmq_producer_group
  producer-timeout: 300000